website/accounts/urls.py
from django.urls import path 
from . import views

app_name= "accounts"

urlpatterns = [
    path("welcome/",views.welcome,name='welcome'),
    path("register/",views.user_register,name="register"),
    path("login/",views.user_login ,name="login"),
    path("logout/",views.user_logout,name="logout" ),
    path("profile/",views.user_profile,name="profile"),
    path("update/",views.user_update,name = "update"),
    path("change_password/",views.user_change_password,name= "change_password"),
    path("login_phone/",views.user_login_phone,name="login_phone"),
    path("verify/",views.verify,name= "verify"),
    path("active/<uidb64>/<token>/",views.RegisterEmial.as_view(),name='active'),
    path("reset/",views.ResetPassword.as_view(),name='reset'),
    path("reset/done/",views.DonePassword.as_view(),name='reset_done'),
    path("confirm/<uidb64>/<token>/",views.ConfirmPassword.as_view(),name='password_reset_confirm'),
    path("confirm/done/",views.Complete.as_view(),name='complete'),
    path('favourite/',views.favourite,name='favourite'),
    path('history/',views.history,name='history'),
    path('profile_com/',views.profile_com,name='profile_com'),
    

]

website/blog/urls.py
from django.urls import path 
from . import views

app_name= "blog"
urlpatterns = [

    path("",views.blog,name="blog"),
    path('detail/<int:id>',views.detail,name='detail'),
    path('dastebandi/<int:id>',views.dastebandi,name='dastebandi'),
   
]

website/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns=[
    path('',views.home, name="home"),
    path('product/',views.product,name= "product"),
    path("detail/<int:id>/",views.detail_product,name= "detail"),
    path("category/<slug>/<int:id>/",views.product,name= "category"),
    path('like/<int:id>/',views.product_like,name="product_like"),
    path('unlike/<int:id>/',views.product_unlike,name="product_unlike"),
    path('comment/<int:id>/',views.product_comment,name="product_comment"),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name="product_reply"),
    path('comment_like/<int:id>',views.comment_like,name="comment_like"),
    path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>',views.favourite_product,name='favourite'),
    path('contact/',views.contact,name='contact'),
    path('privacy/',views.privacy,name='privacy'),
    path('remove_com/<int:id>/',views.remove_com,name='remove_com'),
    
    

]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
    path('blog/',include('blog.urls',namespace='blog')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

website/accounts/models.py
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models

from home.models import *

from phone_field import PhoneField
from django_jalali.db import models as jmodels

# this class for profile table in database.
class formprofile(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE,verbose_name = 'کاربر',related_name='userp')
    phone = PhoneField(null=True,blank=True,verbose_name = 'شماره همراه')
    address = models.CharField(max_length=50,null=True,blank=True,verbose_name = 'آدرس')
    profile_image = models.ImageField(upload_to = 'profile/',default="",null =True,blank=True,verbose_name = 'عکس پروفایل')

    class Meta:
        verbose_name = 'پروفایل'
        verbose_name_plural = 'پروفایل ها '

    def __str__(self) :
        return self.user.username

   
# this function use for auto complate profile information with fillout regsiter form from user.
def profile_signals(sender,**kwargs):
    if kwargs["created"]:
        profile_user = formprofile(user = kwargs["instance"])
        profile_user.save() 

post_save.connect(profile_signals,sender= User)

website/accounts/forms.py
from django.contrib.auth.models import User
from django import forms

from .models import *

# this class for user register form.
class UserregisterForm(forms.Form):
    user_name= forms.CharField(max_length=50,widget=forms.TextInput(attrs={'placeholder':"enter your username"}))
    email= forms.EmailField(widget=forms.EmailInput(attrs={'placeholder':'enter your email'}))
    first_name= forms.CharField(max_length=50,widget=forms.TextInput(attrs={'placeholder':"enter your first name"}))
    last_name= forms.CharField(max_length=50 , widget=forms.TextInput(attrs={"placeholder":'enter your last name'}))
    password_1= forms.CharField(max_length=20, widget = forms.PasswordInput(attrs={"placeholder":"enter your password"}))
    password_2= forms.CharField(max_length=20,widget=forms.PasswordInput(attrs={'placeholder':'enter your password again'}))

    # user name must not exist in database.
    def clean_user_name(self):
        user = self.cleaned_data["user_name"]
        if User.objects.filter(username=user).exists():
            raise forms.ValidationError("username is exist, please change it !!!")
        return user
    
    # email must not exist in database.
    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("this email is exist !!!")
        return email

    # password is to simillar.
    def clean_password_2(self):
        password1 = self.cleaned_data["password_1"]
        password2 = self.cleaned_data["password_2"]
        if password1 != password2:
            raise forms.ValidationError("password not a unique")
        elif len(password2)<3:
            raise forms.ValidationError("this password is short")
        elif not any (x.isupper() for x in password2 ):
            raise forms.ValidationError("you must use capitalize letter")
        return password1

# this class for user login form.
class UserloginForm(forms.Form):
    user = forms.CharField(max_length=50)
    password = forms.CharField(max_length=20)
    remember = forms.BooleanField(required=False,widget=forms.CheckboxInput())

# this class for profile update form user register.
class User_updateform(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email','first_name','last_name']

# this class for profile update form.
class Profile_updateform(forms.ModelForm):
    class Meta:
        model = formprofile
        fields = ['phone','address','profile_image']
        
# this class for login phone form.
class PhoneForm(forms.Form):
    phone = forms.IntegerField()

# this class for code form. 
class CodeForm(forms.Form):
    code = forms.IntegerField()

website/accounts/views.py
from django.contrib import messages
from django.contrib.auth import(
    authenticate,
    login,
    logout,
    update_session_auth_hash,
    views as auth_views,
    ) 

from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes ,force_str
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.shortcuts import redirect, render,reverse
from django.db.models import Q,Max,Min,Sum
from django.core.mail import EmailMessage
from django.views.generic import TemplateView
from django.views import View
from django.urls import reverse_lazy

from .forms import *
from .models import *
from order.models import *
from cart.models import *


from random import randint
from six import text_type
from kavenegar import *

try:
        import json
except ImportError:
        import simplejson as json


# this class for generating a email token.
class EmailToken(PasswordResetTokenGenerator):
    def _make_hash_value(self, user, timestamp):
        return (text_type(user.is_active) + text_type(user.id) + text_type(timestamp))
email_generator = EmailToken()


# this function for user register.
def user_register(request):
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    if request.user.is_authenticated:
        compare = Compare.objects.filter(user_id = request.user.id)
    else:
        compare = Compare.objects.filter(session_key__exact = request.session.session_key,user_id =None)
    category = Category.objects.filter(sub_cat = False)
    if request.method == "POST":
        form= UserregisterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = User.objects.create_user(username=data['user_name'], email=data['email'],first_name=data['first_name'],
                                    last_name=data['last_name'],password=data['password_2'])
            user.is_active = False
            user.save()
            domain = get_current_site(request).domain
            uidb64 = urlsafe_base64_encode(force_bytes(user.id)) 
            url  = reverse('accounts:active',kwargs ={'uidb64':uidb64,'token':email_generator.make_token(user)})
            link = 'http://'+domain+ url
            email = EmailMessage(
                'active user',
                link,
                'test<pouriael2002@gmail.com>',
                [data["email"]]
            )
            email.send(fail_silently=False)
            messages.warning(request,"please wait for activate ...",'warning')
            return redirect('accounts:welcome')
        else:
            messages.success(request,"your are not registered","danger")
    else:
        form = UserregisterForm()
    context = {"form":form,'category':category,'compare':compare,'nums':nums} 
    return render(request,'accounts/register.html',context)

# this function for login user to website.
def user_login(request):
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    if request.user.is_authenticated:
        compare = Compare.objects.filter(user_id = request.user.id)
        
    else:
        compare = Compare.objects.filter(session_key__exact = request.session.session_key,user_id =None)
        
    category = Category.objects.filter(sub_cat = False)
    if request.method == "POST":
        form = UserloginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            remember = data['remember']
            try:
                user = authenticate(request,username =User.objects.get(email=data["user"]), password = data['password'])
            except:
                user = authenticate(request,username=data['user'], password = data['password'])
            if user is not None:
                login(request,user)
                if not remember:
                    request.session.set_expiry(0)
                else:
                    request.session.set_expiry(172800)
                messages.success(request,"welcome to my website",'success')
                return redirect("home:home")
            else:
                messages.error(request,"your login has error","danger")
    else:
        form = UserloginForm()
    context = {"form":form,'category':category,'compare':compare,'nums':nums}
    return render(request,"accounts/login.html",context )

# this function for user logout.
def user_logout(request):
    logout(request)
    messages.success(request,"success logout","success")
    return redirect("home:home")

# this class for activate user account.
class RegisterEmial(View):
    def get(self,request,uidb64,token):
        id = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(id = id)
        if user and email_generator.check_token(user,token):
            user.is_active = True
            user.save()
        return redirect('accounts:login')

# this function for user profile.
@login_required(login_url="accounts:login")
def user_profile(request):
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    if request.user.is_authenticated:
        compare = Compare.objects.filter(user_id = request.user.id)
        
    else:
        compare = Compare.objects.filter(session_key__exact = request.session.session_key,user_id =None)
    category = Category.objects.filter(sub_cat = False)
    Profile = formprofile.objects.get(user_id = request.user.id)
    favourite = request.user.fa_user.all()
    history = ItemOrder.objects.filter(user_id = request.user.id)[:5]
    suggest = Product.objects.all().order_by('-create')
    return render(request,"accounts/profile.html",{"Profile":Profile,"category":category,'compare':compare,'nums':nums,'favourite':favourite,'history':history,'suggest':suggest})

# this function for update user profile.
@login_required(login_url="accounts:login")
def user_update(request):
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    Profile = formprofile.objects.get(user_id = request.user.id)
    if request.user.is_authenticated:
        compare = Compare.objects.filter(user_id = request.user.id)
        
    else:
        compare = Compare.objects.filter(session_key__exact = request.session.session_key,user_id =None)
    category = Category.objects.filter(sub_cat = False)
    if request.method == "POST":
        user_form = User_updateform(request.POST,instance=request.user)
        profile_form = Profile_updateform(request.POST,request.FILES,instance=request.user.userp)
        if profile_form and user_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,"update completed","success")
            return redirect("accounts:profile")
    else:
        user_form = User_updateform(instance=request.user)
        profile_form = Profile_updateform(instance = request.user.userp)
    suggest = Product.objects.all().order_by('-create')
    context = {"user_form":user_form,"profile_form":profile_form,'category':category,'compare':compare,'Profile':Profile,'nums':nums,'suggest':suggest}
    return render (request,"accounts/update.html",context)

# this function for user change password.
@login_required
def user_change_password(request):
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    if request.user.is_authenticated:
        compare = Compare.objects.filter(user_id = request.user.id)
        
    else:
        compare = Compare.objects.filter(session_key__exact = request.session.session_key,user_id =None)
        
    category = Category.objects.filter(sub_cat = False)
    if request.method == "POST":
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            messages.success(request,"password changed","success")
        else:
            messages.error(request,"password is not changed","danger")
    else:
        form  = PasswordChangeForm(request.user)
    context = {"form":form,'categroy':category,'compare':compare,'nums':nums}
    return render(request,"accounts/change.html",context)

# this function for login with phone and user kavenegar api. 
def user_login_phone(request):
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    if request.user.is_authenticated:
        compare = Compare.objects.filter(user_id = request.user.id)
        
    else:
        compare = Compare.objects.filter(session_key__exact = request.session.session_key,user_id =None)
    category = Category.objects.filter(sub_cat = False)
    global random_code,phone
    if request.method == "POST":
        form = PhoneForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            phone =f"0{data['phone']}"
            random_code = randint(100,1000)
            
            api = KavenegarAPI('476E424C59544259596E592F7435595155645A3270385A505A704E58475676394E4E6B6B794A397A5A6B383D')
            params = { 'sender' : '	10008663', 'receptor': phone, 'message' : f'کد تایید هویت شما{random_code}'}
            response = api.sms_send(params)
            print(str(response)) 
            return redirect("accounts:verify")
    else:
        form = PhoneForm()
    context = {"form":form,"category":category,'compare':compare,'nums':nums} 
    return render(request,"accounts/login_phone.html",context)

# this function for verify code sended with kavenegar and user import.
def verify(request):
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    if request.user.is_authenticated:

website/accounts/templates/accounts/complete.html
{% extends 'base.html' %}

{% block body %}
<div style="background-color:dimgrey;padding:30px;width: 500px;margin-left: 370px;margin-top: 30px; border-radius: 10px;">  <h2 style="color:forestgreen;text-align:center;"> you can login to website</h2></div>
  
{% endblock body %}
    

website/accounts/templates/accounts/done.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<div class="wrapper">

       
    <main class="main-content dt-sl mb-3">
<div class="container main-container">
            <div class="row">
                <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                    <div class="logo-area text-center mb-3">
                        <a href="#"><img src="{% static 'assets/img/logo.png'%}" class="img-fluid" alt="logo"></a>
                    </div>
                    <div class="auth-wrapper form-ui border pt-4">
                        <div class="section-title title-wide mb-1 no-after-title-wide">
                         <h2 style='text-align:center'>لطفا ایمیل خود را چک کنید </h2>
                        </div>
                        
                        
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- End main-content -->
    <!-- Start mini-footer -->
    <footer class="mini-footer dt-sl">
        <div class="container main-container">
            <div class="row">
                <div class="col-12">
                    <ul class="mini-footer-menu">
                        <li><a href="#">درباره دیدیکالا</a></li>
                        <li><a href="#">فرصت های شغلی</a></li>
                        <li><a href="#">تماس با ما</a></li>
                        <li><a href="#">همکاری با سازمان ها</a></li>
                    </ul>
                </div>
                <div class="col-12 mt-2 mb-3">
                    <div class="footer-light-text">
                        استفاده از مطالب فروشگاه اینترنتی دیدیکالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع
                        است. کلیه حقوق این سایت متعلق به (فروشگاه آنلاین دیدیکالا) می‌باشد.
                    </div>
                </div>
                <div class="col-12 text-center">
                    <div class="copy-right-mini-footer">
                        Copyright © 2019 Didikala
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End mini-footer -->
  </div>
{% endblock body %}
    

website/accounts/templates/accounts/link.html
<div style="background-color:dimgrey;padding:30px;width: 500px;margin-left: 370px;margin-top: 30px; border-radius: 10px;">  <h2 style="color:forestgreen;text-align:center;"> click to link for change password</h2></div>

{{protocol}}://{{domain}}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

website/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="fa">


{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="theme-color" content="#f7858d">
<meta name="msapplication-navbutton-color" content="#f7858d">
<meta name="apple-mobile-web-app-status-bar-style" content="#f7858d">
<title>didikala | Login Page</title>
<!-- Font Icon -->
<link rel="stylesheet" href= "{% static 'assets/css/vendor/font-awesome.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/materialdesignicons.min.css'%}">
<!-- Bootstrap -->
<link rel="stylesheet" href= "{% static 'assets/css/vendor/bootstrap.min.css'%}">
<!-- Plugins -->
<link rel="stylesheet" href= "{% static 'assets/css/vendor/bootstrap-slider.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/owl.carousel.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/jquery.horizontalmenu.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/jquery-stack-menu.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/fancybox.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/nice-select.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/nouislider.min.css'%}">
<!-- Main CSS File -->
<link rel="stylesheet" href= "{% static 'assets/css/main.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/colors/default.css'%}" id="colorswitch">
{% endblock head %}
  

{% block body %}
  <div class="wrapper">

       
            <main class="main-content dt-sl mb-3">
      <div class="container main-container">
          <div class="row">
              <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                  <div class="logo-area text-center mb-3">
                      <a href="#"><img src="{% static 'assets/img/logo.png'%}" class="img-fluid" alt="logo"></a>
                  </div>
                  <div class="auth-wrapper form-ui border pt-4">
                      <div class="section-title title-wide mb-1 no-after-title-wide">
                          <h2 class="font-weight-bold">ورود</h2>
                      </div>
                      <form method="post">
                        {% csrf_token %}
                          <div class="form-row-title">
                              <h3>ایمیل یا شماره موبایل</h3>
                          </div>
                          <div class="form-row with-icon">
                              <input type="text" class="input-ui pr-2" name="user" maxlength="100" id="id_user"
                                  placeholder="ایمیل یا شماره موبایل خود را وارد نمایید">
                              <i class="mdi mdi-account-circle-outline"></i>
                          </div>
                          <div class="form-row-title">
                              <h3>رمز عبور</h3>
                          </div>
                          <div class="form-row with-icon">
                              <input type="password" class="input-ui pr-2" name="password" maxlength="50" id="id_password"
                                  placeholder="رمز عبور خود را وارد نمایید">
                              <i class="mdi mdi-lock-open-variant-outline"></i>
                          </div>
                          <div class="form-row mt-2">
                              <div class="custom-control custom-checkbox float-right mt-2">
                                  <input type="checkbox" class="custom-control-input" name="remember"  id="customCheck3">
                                  <label class="custom-control-label" for="customCheck3">
                                      مرا به خاطر بسپار
                                  </label> <br><br>
                                  <a style='color:#f7858d;' href="{%url 'accounts:reset' %}">رمز خود را فراموش کردم</a>
                              </div>
                          </div>
                          <div class="form-row mt-3">
                              <button class="btn-primary-cm btn-with-icon mx-auto w-100" type="submit"> 
                                  <i class="mdi mdi-login-variant"></i>
                                  ورود به دیدیکالا
                              </button>
                          </div>
                      </form>
                      <div class="form-footer mt-3">
                          <div>
                              <span class="font-weight-bold">کاربر جدید هستید؟</span>
                              <a href="{%url 'accounts:register' %}" class="mr-3 mt-2">ثبت نام در دیدیکالا</a>
                              
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </main>
  <!-- End main-content -->
  <!-- Start mini-footer -->
  <footer class="mini-footer dt-sl">
      <div class="container main-container">
          <div class="row">
              <div class="col-12">
                  <ul class="mini-footer-menu">
                      <li><a href="#">درباره دیدیکالا</a></li>
                      <li><a href="#">فرصت های شغلی</a></li>
                      <li><a href="#">تماس با ما</a></li>
                      <li><a href="#">همکاری با سازمان ها</a></li>
                  </ul>
              </div>
              <div class="col-12 mt-2 mb-3">
                  <div class="footer-light-text">
                      استفاده از مطالب فروشگاه اینترنتی دیدیکالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع
                      است. کلیه حقوق این سایت متعلق به (فروشگاه آنلاین دیدیکالا) می‌باشد.
                  </div>
              </div>
              <div class="col-12 text-center">
                  <div class="copy-right-mini-footer">
                      Copyright © 2019 Didikala
                  </div>
              </div>
          </div>
      </div>
  </footer>
  <!-- End mini-footer -->
</div>
<!-- colorPanel -->

<!-- end colorPanel -->
<!-- Core JS Files -->
<script src="{% static 'assets/js/vendor/jquery-3.4.1.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/popper.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js'%}"></script>
<!-- Plugins -->
<script src="{% static 'assets/js/vendor/bootstrap-slider.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/owl.carousel.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/owl.carousel2.thumbs.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.nicescroll.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/nouislider.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.horizontalmenu.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery-stack-menu.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.fancybox.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/countdown.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/wNumb.js'%}"></script>
<script src="{% static 'assets/js/vendor/ResizeSensor.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/theia-sticky-sidebar.min.js'%}"></script>
<!-- Main JS File -->
<script src="{% static 'assets/js/main.js'%}"></script>
{% endblock body %}
  


</html>

website/accounts/templates/accounts/login_phone.html
{% extends "base.html" %}
{% load static %}
{% load jformat%}
<!DOCTYPE html>
<html lang="fa">
{% block title%} login phone {% endblock title%}

{% block body %} 
<div class="wrapper">

       
    <main class="main-content dt-sl mb-3">
<div class="container main-container">
            <div class="row">
                <div class="col-xl-4 col-lg-5 col-md-7 col-12 mx-auto">
                    <div class="logo-area text-center mb-3">
                        <a href="#"><img src="{% static 'assets/img/logo.png'%}" class="img-fluid" alt="logo"></a>
                    </div>
                    <div class="auth-wrapper form-ui border pt-4">
                        <div class="section-title title-wide mb-1 no-after-title-wide">
                            <h2 class="font-weight-bold">ورود</h2>
                        </div>
                        <form method="post">
                          {% csrf_token %}
                            <div class="form-row-title">
                                <h3> شماره موبایل</h3>
                            </div>
                            <div class="form-row with-icon">
                                <input type="text" class="input-ui pr-2" name="phone" maxlength="100" id="id_user"
                                    placeholder=" شماره موبایل خود را وارد نمایید">
                                <i class="mdi mdi-account-circle-outline"></i>
                            </div>
                            <div class="form-row mt-3">
                                <button class="btn-primary-cm btn-with-icon mx-auto w-100" type="submit"> 
                                    <i class="mdi mdi-login-variant"></i>
                                ارسال کد
                                </button>
                            </div>
                        </form>
                        <div class="form-footer mt-3">
                            <div>
                                <span class="font-weight-bold">کاربر جدید هستید؟</span>
                                <a href="{%url 'accounts:register' %}" class="mr-3 mt-2">ثبت نام در دیدیکالا</a>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- End main-content -->
    <!-- Start mini-footer -->
    <footer class="mini-footer dt-sl">
        <div class="container main-container">
            <div class="row">
                <div class="col-12">
                    <ul class="mini-footer-menu">
                        <li><a href="#">درباره دیدیکالا</a></li>
                        <li><a href="#">فرصت های شغلی</a></li>
                        <li><a href="#">تماس با ما</a></li>
                        <li><a href="#">همکاری با سازمان ها</a></li>
                    </ul>
                </div>
                <div class="col-12 mt-2 mb-3">
                    <div class="footer-light-text">
                        استفاده از مطالب فروشگاه اینترنتی دیدیکالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع
                        است. کلیه حقوق این سایت متعلق به (فروشگاه آنلاین دیدیکالا) می‌باشد.
                    </div>
                </div>
                <div class="col-12 text-center">
                    <div class="copy-right-mini-footer">
                        Copyright © 2019 Didikala
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End mini-footer -->
  </div>

{% endblock body %}