website/accounts/urls.py
from django.urls import path 
from . import views

app_name= "accounts"

urlpatterns = [
    path("welcome/",views.welcome,name='welcome'),
    path("register/",views.user_register,name="register"),
    path("login/",views.user_login ,name="login"),
    path("logout/",views.user_logout,name="logout" ),
    path("profile/",views.user_profile,name="profile"),
    path("update/",views.user_update,name = "update"),
    path("change_password/",views.user_change_password,name= "change_password"),
    path("login_phone/",views.user_login_phone,name="login_phone"),
    path("verify/",views.verify,name= "verify"),
    path("active/<uidb64>/<token>/",views.RegisterEmial.as_view(),name='active'),
    path("reset/",views.ResetPassword.as_view(),name='reset'),
    path("reset/done/",views.DonePassword.as_view(),name='reset_done'),
    path("confirm/<uidb64>/<token>/",views.ConfirmPassword.as_view(),name='password_reset_confirm'),
    path("confirm/done/",views.Complete.as_view(),name='complete'),
    path('favourite/',views.favourite,name='favourite'),
    path('history/',views.history,name='history'),
    path('profile_com/',views.profile_com,name='profile_com'),
    

]

website/blog/urls.py
from django.urls import path 
from . import views

app_name= "blog"
urlpatterns = [

    path("",views.blog,name="blog"),
    path('detail/<int:id>',views.detail,name='detail'),
    path('dastebandi/<int:id>',views.dastebandi,name='dastebandi'),
   
]

website/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('',views.cart_detail,name ='cart_detail'),
    path('add/<int:id>/',views.add_cart,name="add_cart"),
    path('remove/<int:id>/',views.remove_cart,name="remove_cart"),
    path('remove_single/<int:id>/',views.remove_single,name="remove_single"),
    path('add_single/<int:id>/',views.add_single,name="add_single"),
    path('compare/<int:id>/',views.compare,name="compare"),
    path('compare_remove/<int:id>/',views.compare_remove,name='compare_remove'),
    path('show/',views.show,name="show"),
    path('compare_filter/',views.compare_filter,name='compare_filter')
]

website/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns=[
    path('',views.home, name="home"),
    path('product/',views.product,name= "product"),
    path("detail/<int:id>/",views.detail_product,name= "detail"),
    path("category/<slug>/<int:id>/",views.product,name= "category"),
    path('like/<int:id>/',views.product_like,name="product_like"),
    path('unlike/<int:id>/',views.product_unlike,name="product_unlike"),
    path('comment/<int:id>/',views.product_comment,name="product_comment"),
    path('reply/<int:id>/<int:comment_id>/',views.product_reply,name="product_reply"),
    path('comment_like/<int:id>',views.comment_like,name="comment_like"),
    path('search/',views.product_search,name='product_search'),
    path('favourite/<int:id>',views.favourite_product,name='favourite'),
    path('contact/',views.contact,name='contact'),
    path('privacy/',views.privacy,name='privacy'),
    path('remove_com/<int:id>/',views.remove_com,name='remove_com'),
    
    

]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
    path('blog/',include('blog.urls',namespace='blog')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

website/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">

<html>
    <head>
        <title>{% block title%}{% endblock title%}</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.1.1/css/fontawesome.min.css" integrity="sha384-zIaWifL2YFF1qaDiAo0JFgsmasocJ/rqu7LKYH8CoBEXqGbb9eO+Xi3s6fQhgFWM" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
        <link rel='stylesheet' href='https://sachinchoolur.github.io/lightslider/dist/css/lightslider.css'>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="theme-color" content="#f7858d">
        <meta name="msapplication-navbutton-color" content="#f7858d">
        <meta name="apple-mobile-web-app-status-bar-style" content="#f7858d">
        <title>didikala | Blog Page</title>
        <!-- Font Icon -->
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/font-awesome.min.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/materialdesignicons.min.css'%}">
        <!-- Bootstrap -->
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/bootstrap.min.css'%}">
        <!-- Plugins -->
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/bootstrap-slider.min.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/owl.carousel.min.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/jquery.horizontalmenu.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/jquery-stack-menu.min.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/fancybox.min.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/nice-select.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/vendor/nouislider.min.css'%}">
        <!-- Main CSS File -->
        <link rel="stylesheet" href= "{% static 'assets/css/main.css'%}">
        <link rel="stylesheet" href= "{% static 'assets/css/colors/default.css'%}" id="colorswitch">
        {% block head%} {% endblock head%}
    </head>
    <body class="main">
        {% include "navbar.html" %}
        {% include "messages.html" %}
        {% block body %}{% endblock body %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        {% block script %}{% endblock script %}
        <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
        <script src="{% static 'assets/js/vendor/jquery-3.4.1.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/popper.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js'%}"></script>
<!-- Plugins -->
<script src="{% static 'assets/js/vendor/bootstrap-slider.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/owl.carousel.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/owl.carousel2.thumbs.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.nicescroll.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/nouislider.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.horizontalmenu.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery-stack-menu.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.fancybox.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/countdown.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/wNumb.js'%}"></script>
<script src="{% static 'assets/js/vendor/ResizeSensor.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/theia-sticky-sidebar.min.js'%}"></script>
<!-- Main JS File -->
<script src="{% static 'assets/js/main.js'%}"></script>
    </body>
</html>

website/templates/messages.html
{% if messages%}
{% for msg in messages%}
<div id="msg">
    <h3 role="alert" {% if msg.tags %} class="alert alert-{{msg.tags}}" {% endif %}>{{msg}}</h3>
</div>
    
    {% block script %}
<script>
    var message_ele = document.getElementById("msg");

setTimeout(function(){ 
   message_ele.style.display = "none"; 
}, 3000);
</script>

    {% endblock script %}
   
{% endfor %}
{% endif %}

website/templates/navbar.html
<!DOCTYPE html>
<html lang="fa">

{% load static %}
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="theme-color" content="#f7858d">
<meta name="msapplication-navbutton-color" content="#f7858d">
<meta name="apple-mobile-web-app-status-bar-style" content="#f7858d">
<title>didikala | Blog Page</title>
<!-- Font Icon -->
<link rel="stylesheet" href= "{% static 'assets/css/vendor/font-awesome.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/materialdesignicons.min.css'%}">
<!-- Bootstrap -->
<link rel="stylesheet" href= "{% static 'assets/css/vendor/bootstrap.min.css'%}">
<!-- Plugins -->
<link rel="stylesheet" href= "{% static 'assets/css/vendor/bootstrap-slider.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/owl.carousel.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/jquery.horizontalmenu.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/jquery-stack-menu.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/fancybox.min.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/nice-select.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/vendor/nouislider.min.css'%}">
<!-- Main CSS File -->
<link rel="stylesheet" href= "{% static 'assets/css/main.css'%}">
<link rel="stylesheet" href= "{% static 'assets/css/colors/default.css'%}" id="colorswitch">
</head>
<header class="main-header" dir="rtl">
  <!-- Start ads -->
  <div class="ads-header-wrapper">
    <a href="#" class="ads-header hidden-sm" target="_blank"
        style="background-image: url('{% static 'assets/img/banner/large-ads.jpg' %}') "></a>
</div>
  <!-- End ads -->
  <!-- Start topbar -->
  <div class="container main-container">
      <div class="topbar dt-sl">
          <div class="row">
              <div class="col-lg-2 col-md-3 col-6">
                  <div class="logo-area">
                      <a href="#">
                          <img src="{% static 'assets/img/logo.png'%}" alt="">
                      </a>
                  </div>
              </div>
              <div class="col-lg-7 col-md-6 hidden-sm">
                  <div class="search-area dt-sl">
                      <form action="{% url 'home:product' %}" class="search">
                          {% csrf_token %}
                          <input type="search" name="search"
                              placeholder="نام کالا، برند و یا دسته مورد نظر خود را جستجو کنید…">
                          <i class="far fa-search search-icon"></i>
                          <button class="close-search-result" type="button"><i
                                  class="mdi mdi-close"></i></button>
                      </form>
                  </div>
              </div>
              <div class="col-md-3 col-2 topbar-left">
                  <ul class="nav float-left"style="background-color:#fff">
                      <li class="nav-item account dropdown">
                          <a class="nav-link" href="#" data-toggle="dropdown" aria-haspopup="true" 
                              aria-expanded="false">
                              <span class="label-dropdown">حساب کاربری</span>
                              <i class="mdi mdi-account-circle-outline"></i>
                          </a>
                          
                          <div class="dropdown-menu dropdown-menu-sm dropdown-menu-left">
                              {% if  user.is_authenticated %}
                              <a class="dropdown-item" href="{% url 'accounts:profile' %}">
                                  <i class="mdi mdi-account-card-details-outline"></i>پروفایل
                              </a>
                              <a class="dropdown-item" href="{% url 'accounts:update' %}">
                                  <i class="mdi mdi-account-edit-outline"></i>ویرایش حساب کاربری
                              </a>
                              <div class="dropdown-divider" role="presentation"></div>
                              
                              <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                                  <i class="mdi mdi-logout-variant"></i>خروج
                              </a>
                              {% else %}
                              <a class="dropdown-item" href="{% url 'accounts:login' %}">
                                  <i class="mdi mdi-account-card-details-outline"></i>ورود
                              </a>
                              <a class="dropdown-item" href="{% url 'accounts:register' %}">
                                  <i class="mdi mdi-account-edit-outline"></i>ثبت نام
                              </a>
                              {% endif %}
                          </div>
                      </li>
                  </ul>
                  
              </div>
          </div>
      </div>
  </div>
  <!-- End topbar -->

  <!-- Start bottom-header -->
  <div class="bottom-header dt-sl mb-sm-bottom-header">
      <div class="container main-container">
          <!-- Start Main-Menu -->
          <nav class="main-menu d-flex justify-content-md-between justify-content-end dt-sl">
              <ul class="list hidden-sm">
                  <li class="list-item category-list">
                      <a href="#"><i class="fal fa-bars ml-1"></i>دسته بندی کالاها</a>
                      <ul>
                          {% for cat in category %}
                          <li>
                              <a href="{{cat.get_absolute_url}}"> {{cat.name}}</a>
                              <ul class="row">
                                  {% for data in cat.sub.all  %}
                                  <li class="sublist--title"><a href="{{data.get_absolute_url}}"> {{data.name}}</a></li>
                                  {% endfor %}   
                              </ul>
                          </li>
                          {% endfor %}
                          
                          
                      </ul>
                      
                  </li>
                  <li class="list-item " >
                      <a href="{% url 'home:home'%}"><i class="fal fa-home ml-1"></i>خانه</a>
                  </li>
                  <li class="list-item " >
                      <a href="{% url 'home:product'%}"><i class="fas fa-tshirt ml-1"></i>محصولات</a>
                  </li>
                  <li class="list-item " >
                      <a href="{% url 'blog:blog'%}"><i class="fal fa-book ml-1"></i>بلاگ</a>
                  </li>
                  <li class="list-item " >
                      <a href="{% url 'home:contact'%}"><i class="fal fa-phone ml-1"></i>ارتباط با ما</a>
                  </li>
                  {% if  user.is_authenticated %}
                  <li class="list-item " >
                    <a href="{% url 'cart:show'%}"><i class="fa-solid fa-code-compare"></i>لیست مقایسه</a>
                  </li>
                  {% endif %}
                  
              </ul>
              <div class="nav mr-auto" style="background-color:#fff">
                  <div class="nav-item cart--wrapper">
                      <a class="nav-link" href="{% url 'cart:cart_detail'%}">
                          <span class="label-dropdown">سبد خرید</span>
                          <i class="mdi mdi-cart-outline"></i>
                          <span class="count"> {% if nums != None %} {{nums}} {% else %} 0 {% endif %}</span>
                      </a>
                      
                  </div>
              </div>
              
              <button class="btn-menu">
                  <div class="align align__justify">
                      <span></span>
                      <span></span>
                      <span></span>
                  </div>
              </button>
          </nav>
          <!-- End Main-Menu -->
      </div>
  </div>
  <!-- End bottom-header -->
</header>
<script src="{% static 'assets/js/vendor/jquery-3.4.1.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/popper.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js'%}"></script>
<!-- Plugins -->
<script src="{% static 'assets/js/vendor/bootstrap-slider.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/owl.carousel.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/owl.carousel2.thumbs.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.nicescroll.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/nouislider.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.horizontalmenu.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery-stack-menu.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/jquery.fancybox.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/countdown.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/wNumb.js'%}"></script>
<script src="{% static 'assets/js/vendor/ResizeSensor.min.js'%}"></script>
<script src="{% static 'assets/js/vendor/theia-sticky-sidebar.min.js'%}"></script>
<!-- Main JS File -->
<script src="{% static 'assets/js/main.js'%}"></script>