website/blog/urls.py
from django.urls import path 
from . import views

app_name= "blog"
urlpatterns = [

    path("",views.blog,name="blog"),
    path('detail/<int:id>',views.detail,name='detail'),
    path('dastebandi/<int:id>',views.dastebandi,name='dastebandi'),
   
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls',namespace='home')),
    path('accounts/',include('accounts.urls',namespace="accounts")),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('order/',include('order.urls',namespace='order')),
    path('blog/',include('blog.urls',namespace='blog')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

website/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Avg

from accounts.models import * 

from ckeditor_uploader.fields import RichTextUploadingField 
from taggit.managers import TaggableManager
from django_jalali.db import models as jmodels


# this class for blog table in database.
class Blog(models.Model):
    name = models.CharField(max_length=200,verbose_name='اسم')
    create = jmodels.jDateTimeField(auto_now_add=True)
    update = jmodels.jDateTimeField(auto_now=True)
    image = models.ImageField(upload_to='blog')
    tags =  TaggableManager(blank=True,verbose_name = 'نسبت تشابه')
    text = RichTextUploadingField(blank =True,null=True)
    kholase = models.CharField(max_length=500,default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.')
    views = models.ManyToManyField(User,blank=True,related_name='views_blog')
    total_views = models.IntegerField(null=True,blank=True,default=0)
    total = models.IntegerField(default=0)


    def total_views(self):
        return self.views.count()

    def total_asli(self):
        data = self.total_views()+self.total
        return data

    def __str__(self):
        return self.name

website/blog/views.py
from django.shortcuts import(
    redirect,
    render ,
    get_object_or_404,render
    ) 
from django.db.models import Q,Max,Min,Sum
from django.core.paginator import Paginator

from .models import *
from .filters import *
from home.models import *
from cart.models import *

# this function for all blog.
def blog(request):
    cart = Cart.objects.filter(user_id = request.user.id)
    total = 0
 
    for p in cart:
        if p.product.status != "None":
            total += p.variants.total_price * p.quantity
        else:
            total += p.quantity * p.product.total_price 
    nums = Cart.objects.filter(user_id =request.user.id ).aggregate(sum=Sum('quantity'))['sum']
    blog = Blog.objects.all()
    create = Blog.objects.all().order_by('-create')[:5]
    tag = Blog.tags.all()
    paginator = Paginator(blog,6)
    page_num = request.GET.get('page')
    data = request.GET.copy()
    if 'page' in data:
        del data['page']
    page_obj = paginator.get_page(page_num)
    category = Category.objects.filter(sub_cat = False)
    return render(request,"blog/blog.html",{'blog':blog ,'nums':nums,'total':total,'create':create,'tag':tag,'data':data,'blogs':page_obj,'page_num':page_num,'category':category})

# this function for detail blog
def detail(request,id):
    blog = get_object_or_404(Blog,id = id)
    blog_all = Blog.objects.all()
    filter = BlogFilter(request.GET,queryset=blog_all)
    blog_all = filter.qs
    create = Blog.objects.all().order_by('-create')[:5]
    bazdid = sorted(blog_all,key= lambda t: t.total_asli(),reverse=True)
    tag = Blog.tags.all()
    similar = blog.tags.similar_objects()
    if request.user.is_authenticated:
        blog.views.add(request.user)
    else :
        blog.total += 1
        blog.save()
    views = blog.total_asli()
    return render(request,"blog/detail.html",{'blog':blog,'views':views,'filter':filter,'blog_all':blog_all,'create':create,'bazdid':bazdid,'similar':similar,'tag':tag})

# this function for category blog
def dastebandi(request,id):
    tag =  Blog.tags.get(id =id)
    blog = Blog.objects.filter(tags =tag)
    
    return render(request,'blog/dastebandi.html',{'tag':tag,'blog':blog})

website/blog/templates/blog/dastebandi.html
{% extends 'base.html' %}
{% load static %}
{% load jformat %}
{% block title%} blog {% endblock title%}
{% block head%} 
<link rel="stylesheet" href="{% static 'blog/blog.css'%}"> 
{% endblock head %}
{% block body %}
<h1 style="color:darkgreen"> دسته بندی {{tag}}</h1>
<div class="container">
    <div class="row">
      
      
      
        {% for i in blog %}
        <div class="col-md-4">
            <div class="blog-card blog-card-blog">
              <div class="blog-card-image"> 
                  <a href="{% url "blog:detail" i.id %}"> <img style="width:350px;height:200px;" class="img" src="{{i.image.url}}"> </a>
                  <div class="ripple-cont"></div>
              </div>
              <div class="blog-table">
                  <h6 class="blog-category blog-text-success"><i class="far fa-newspaper"></i></h6>
                  <h4 class="blog-card-caption">
                      <a href="{% url "blog:detail" i.id %}">{{i.name}}</a>
                  </h4>
                  <p> {{i.kholase}}</p>
                  <div class="ftr">
                      
                      <div class="stats">   <span><i style="color:green" class="fas fa-calendar"></i>{{i.create|jformat:' %d %B %Y '}}</span>&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp  &nbsp;
                        <span><i style="color:red" class="fas fa-eye"> </i> {{i.total_asli}}</span></div>
                  </div>
              </div>
          </div>
          </div>
        {% endfor %}
     
    </div>
  </div>
  <style>
      h1{
         text-align:center;
         margin-bottom:50px;
         margin-top:50px;
       }
       a {
         font-family: Roboto;
        }
       .blog-card-blog {
           margin-top: 30px;
       }
       .blog-card {
           display: inline-block;
           position: relative;
           width: 100%;
           margin-bottom: 30px;
           border-radius: 6px;
           color: rgba(0, 0, 0, 0.87);
           background: #fff;
           box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 3px 1px -2px rgba(0, 0, 0, 0.2), 0 1px 5px 0 rgba(0, 0, 0, 0.12);
       }
       .blog-card .blog-card-image {
           height: 60%;
           position: relative;
           overflow: hidden;
           margin-left: 15px;
           margin-right: 15px;
           margin-top: -30px;
           border-radius: 6px;
           box-shadow: 0 16px 38px -12px rgba(0, 0, 0, 0.56), 0 4px 25px 0px rgba(0, 0, 0, 0.12), 0 8px 10px -5px rgba(0, 0, 0, 0.2);
       }
       .blog-card .blog-card-image img {
           width: 100%;
           height: 100%;
           border-radius: 6px;
           pointer-events: none;
       }
       .blog-card .blog-table {
           padding: 15px 30px;
       }
       .blog-table {
           margin-bottom: 0px;
       }
       .blog-category {
           position: relative;
           line-height: 0;
           margin: 15px 0;
       }
       .blog-text-success {
           color: #28a745!important;
       }
       .blog-card-blog .blog-card-caption {
           margin-top: 5px;
       }
       .blog-card-caption {
           font-weight: 700;
           font-family: "Roboto Slab", "Times New Roman", serif;
       }
       .fa {
           display: inline-block;
           font: normal normal normal 14px/1 FontAwesome;
           font-size: inherit;
           text-rendering: auto;
           -webkit-font-smoothing: antialiased;
           -moz-osx-font-smoothing: grayscale;
       }
       .blog-card-caption, .blog-card-caption a {
           color: #333;
           text-decoration: none;
       }
       
       p {
           color: #3C4857;
       }
       
       p {
           margin-top: 0;
           margin-bottom: 1rem;
       }
       .blog-card .ftr {
           margin-top: 15px;
       }
       .blog-card .ftr .author {
           color: #888;
       }
       
       .blog-card .ftr div {
           display: inline-block;
       }
       .blog-card .author .avatar {
           width: 36px;
           height: 36px;
           overflow: hidden;
           border-radius: 50%;
           margin-right: 5px;
       }
       .blog-card .ftr .stats {
         position: relative;
         top: 1px;
         font-size: 14px;
     }
       .blog-card .ftr .stats {
           float: right;
           line-height: 30px;
       }   
     </style>
{% endblock body %}
    

website/blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}
{% load jformat %}
<!DOCTYPE html>
<html lang="fa">




{% block body %}
    <div class="wrapper">
        <!-- Start header -->
        
        <!-- End header -->
        <!-- Start main-content -->
        <main class="main-content dt-sl mb-3">
            <div class="container main-container">
                <!-- Start title - breadcrumb -->
                <div class="title-breadcrumb-special dt-sl">
                    <div class="title-page dt-sl">
                        <h1>{{blog.name}}</h1>
                    </div>
                </div>
                <!-- End title - breadcrumb -->
                <div class="row">
                    <div class="col-lg-9 col-md-8 col-sm-12 col-12 mb-3">
                        <div class="content-page">
                            <div class="content-desc dt-sn dt-sl">
                                <header class="entry-header dt-sl mb-3">
                                    <div class="post-meta date">
                                        <i class="mdi mdi-calendar-month"></i>{{blog.create|jformat:' %d %B %Y '}}
                                    </div>
                                    
                                    <div class="post-meta category">
                                        <i class="mdi mdi-folder"></i>
                                        <a href="#">دسته‌بندی نشده</a> ، <a href="#">کسب و کار آنلاین</a> ، <a
                                            href="#">معرفی کتاب</a>
                                    </div>
                                    <div class="post-meta category">
                                        <i class="mdi mdi-eye"></i>
                                        {{views}} بازدید
                                    </div>
                                </header>
                                <div class="post-thumbnail dt-sl">
                                    <img src="{{blog.image.url}}" alt="">
                                </div>
                                <p>{{blog.text|safe}}</p>
                            </div>
                        </div>
                        
                    </div>
                    <div class="col-lg-3 col-md-4 col-sm-12 col-12 mb-3 sidebar sticky-sidebar">
                        <div class="widget-posts dt-sn dt-sl rounded-0 border-bottom mb-3">
                            <div class="title-sidebar dt-sl mb-3">
                                <h3>جدیدترین نوشته ها</h3>
                            </div>
                            <div class="content-sidebar dt-sl">
                                {% for i in create %}
                                    <div class="item">
                                        <div class="item-inner">
                                            <div class="item-thumb">
                                                <a href="{% url 'blog:detail' i.id %}" class="img-holder"
                                                    style="background-image: url('{{i.image.url}}')"></a>
                                            </div>
                                            <p class="title">
                                                <a href="{% url 'blog:detail' i.id %}">{{i.name}}</a>
                                            </p>
                                            <div class="item-meta">
                                                <span class="time">{{blog.create|jformat:' %d %B %Y '}}</span>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                
                            </div>
                        </div>
                        <div class="dt-sn dt-sl rounded-0 border-bottom mb-3">
                            <div class="section-title text-sm-title title-wide no-after-title-wide mb-1">
                                <h2>دسته ها</h2>
                            </div>
                            <ul class="category-list">
                            
                                {% for i in tag %}
                                <li><a href="{% url 'blog:dastebandi' i.id %}">{{i.name}}</a></li>
                                {% endfor %}
                                    
                                
                            </ul>
                        </div>
                        
                    </div>
                </div>
            </div>
        </main>
        <!-- End main-content -->
        <!-- Start footer -->
        <footer class="main-footer dt-sl">
            <div class="back-to-top">
                <a href="#"><span class="icon"><i class="mdi mdi-chevron-up"></i></span> <span>بازگشت به
                        بالا</span></a>
            </div>
            <div class="container main-container">
                <div class="footer-services">
                    <div class="row">
                        <div class="service-item col">
                            <a href="#" target="_blank">
                                <img src="{% static 'assets/img/svg/delivery.svg'%}">
                            </a>
                            <p>تحویل اکسپرس</p>
                        </div>
                        <div class="service-item col">
                            <a href="#" target="_blank">
                                <img src="{% static 'assets/img/svg/contact-us.svg'%}">
                            </a>
                            <p>پشتیبانی 24 ساعته</p>
                        </div>
                        <div class="service-item col">
                            <a href="#" target="_blank">
                                <img src="{% static 'assets/img/svg/payment-terms.svg'%}">
                            </a>
                            <p>پرداخت درمحل</p>
                        </div>
                        <div class="service-item col">
                            <a href="#" target="_blank">
                                <img src="{% static 'assets/img/svg/return-policy.svg'%}">
                            </a>
                            <p>۷ روز ضمانت بازگشت</p>
                        </div>
                        <div class="service-item col">
                            <a href="#" target="_blank">
                                <img src="{% static 'assets/img/svg/origin-guarantee.svg'%}">
                            </a>
                            <p>ضمانت اصل بودن کالا</p>
                        </div>
                    </div>
                </div>
                <div class="footer-widgets">
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="widget-menu widget card">
                                <header class="card-header">
                                    <h3 class="card-title">راهنمای خرید از تاپ کالا</h3>
                                </header>
                                <ul class="footer-menu">
                                    <li>
                                        <a href="#">نحوه ثبت سفارش</a>
                                    </li>
                                    <li>
                                        <a href="#">رویه ارسال سفارش</a>
                                    </li>
                                    <li>
                                        <a href="#">شیوه‌های پرداخت</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="widget-menu widget card">
                                <header class="card-header">
                                    <h3 class="card-title">خدمات مشتریان</h3>
                                </header>
                                <ul class="footer-menu">
                                    <li>
                                        <a href="#">پاسخ به پرسش‌های متداول</a>
                                    </li>
                                    <li>
                                        <a href="#">رویه‌های بازگرداندن کالا</a>
                                    </li>
                                    <li>
                                        <a href="#">شرایط استفاده</a>
                                    </li>
                                    <li>
                                        <a href="#">حریم خصوصی</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="widget-menu widget card">
                                <header class="card-header">
                                    <h3 class="card-title">با تاپ کالا</h3>
                                </header>
                                <ul class="footer-menu">
                                    <li>
                                        <a href="#">فروش در تاپ کالا</a>
                                    </li>
                                    <li>
                                        <a href="#">همکاری با سازمان‌ها</a>
                                    </li>
                                    <li>
                                        <a href="#">فرصت‌های شغلی</a>
                                    </li>
                                    <li>
                                        <a href="#">تماس با تاپ کالا</a>
                                    </li>
                                    <li>
                                        <a href="#">درباره تاپ کالا</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg-3">
                            <div class="newsletter">
                                <p>از تخفیف‌ها و جدیدترین‌های فروشگاه باخبر شوید:</p>
                                <form action="">
                                    <input type="email" class="form-control"
                                        placeholder="آدرس ایمیل خود را وارد کنید...">
                                    <input type="submit" class="btn btn-primary" value="ارسال">
                                </form>
                            </div>
                            <div class="socials">
                                <p>ما را در شبکه های اجتماعی دنبال کنید.</p>
                                <div class="footer-social">
                                    <ul class="text-center">
                                        <li><a href="#"><i class="mdi mdi-instagram"></i></a></li>
                                        <li><a href="#"><i class="mdi mdi-telegram"></i></a></li>
                                        <li><a href="#"><i class="mdi mdi-facebook"></i></a></li>
                                        <li><a href="#"><i class="mdi mdi-twitter"></i></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="info">
                    <div class="row">
                        <div class="col-12 text-right">
                            <span>هفت روز هفته ، 24 ساعت شبانه‌روز پاسخگوی شما هستیم.</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="description">
                <div class="container main-container">
                    <div class="row">
                        <div class="site-description col-12 col-lg-7">
                            <h1 class="site-title">فروشگاه اینترنتی تاپ کالا، بررسی، انتخاب و خرید آنلاین</h1>
                            <p>
                                تاپ کالا به عنوان یکی از قدیمی‌ترین فروشگاه های اینترنتی با بیش از یک دهه تجربه، با
                                پایبندی به سه اصل کلیدی، پرداخت در
                                محل، 7 روز ضمانت بازگشت کالا و تضمین اصل‌بودن کالا، موفق شده تا همگام با فروشگاه‌های
                                معتبر جهان، به بزرگ‌ترین فروشگاه
                                اینترنتی ایران تبدیل شود. به محض ورود به تاپ کالا با یک سایت پر از کالا رو به رو
                                می‌شوید! هر آنچه که نیاز دارید و به
                                ذهن شما خطور می‌کند در اینجا پیدا خواهید کرد.
                            </p>
                        </div>
                        <div class="symbol col-12 col-lg-5">
                            <a href="#" target="_blank"><img src="{% static 'assets/img/symbol-01.png'%}"alt=""></a>
                            <a href="#" target="_blank"><img src="{% static 'assets/img/symbol-02.png'%}" alt=""></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <div class="container main-container">
                    <p>
                        استفاده از مطالب فروشگاه اینترنتی تاپ کالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع است.
                        کلیه حقوق این سایت متعلق
                        به شرکت نوآوران فن آوازه (فروشگاه آنلاین تاپ کالا) می‌باشد.
                    </p>
                </div>
            </div>
        </footer>
        <!-- End footer -->
    </div>
    <!-- colorPanel -->
{% endblock body %}

</html>